version: '3.8'

services:
  db:
    image: postgres:16
    container_name: book-db
    environment:
      POSTGRES_DB: book
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
